# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-01-11 06:42
from __future__ import unicode_literals

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fileupload',
            field=models.FileField(blank=True, null=True, upload_to=students.models.getFormattedMediaFileName),
        ),
        migrations.AddField(
            model_name='student',
            name='imageUpload',
            field=models.ImageField(blank=True, null=True, upload_to=students.models.getFormattedMediaFileName),
        ),
    ]
